### ISSUE TITLE
Error when working with The Shomate Parameterization

### ISSUE THREAD

**Issue by Dmitriy-Filatov-A** [Cantera/cantera#1018]
Hello! I use the Cantera C++ interface and I ran into a problem when I tried to use The Shomate Parameterization. I created an input yaml-file and wrote "Shomate" in the "species -> thermo -> model" then I wrote the coefficients of the polynomials of this parametrization in the "species -> thermo -> data". The Cantera works correctly if I use species with one or two temperature ranges, for example [298.15, 3000] or [298.15, 3000, 6000] but if I use species with three or more temperature ranges ([298.15, 3000, 6000, 10000, ...]), the Cantera doesn't create phase (however, the yaml-file is read correctly in this case and the error appears only during the creation phase).
How can I solve this problem? Thank you in advance!

**Comment by ischoegl** [comment]
Hi @Dmitriy-Filatov-A ... could you post the error trace back?

**Comment by bryanwweber** [comment]
Hi! Thanks for reporting this. Can you please include a complete example, including the input file and any necessary code to reproduce the error?

**Comment by ischoegl** [comment]
Hi @Dmitriy-Filatov-A ... to follow up. Unless I am overlooking something, I actually believe that Shomate is only implemented for one and two temperature regions, see [C++ class documentation](https://cantera.org/documentation/docs-2.5/doxygen/html/classes.html#letter_S). I'd still be interested to see the YAML input you created and the associated error message.

While I'm not familiar with the details enough, it's likely not too difficult to extend the concept to an implementation with more temperature ranges.

**Comment by Dmitriy-Filatov-A** [comment]
The program in cpp:

```cpp
#include "cantera/thermo.h"
#include "cantera/thermo/IdealGasPhase.h"
#include <iostream>

int main()
{
	auto phase= std::shared_ptr<Cantera::IdealGasPhase>(new Cantera::IdealGasPhase());
	auto yamlMap= Cantera::AnyMap::fromYamlFile("phase.yaml");
	std::vector<std::shared_ptr<Cantera::Species>> m_species;
	m_species= Cantera::getSpecies(yamlMap.at("species"));
	
	for (size_t i= 0; i < m_species.size(); i++) { 
		phase->addSpecies(m_species.at(i));
	}

	phase->setState_TPY(3000.0, 5 * Cantera::OneBar, "O:8, H2:2");
	std::cout << phase->report() << std::endl;
	phase->equilibrate("TP");
	std::cout << phase->report() << std::endl;

	return 0;
}
```

The input-yaml file:

```yaml
species:
  - name: O
    composition:
      O: 1
    thermo:
      model: Shomate
      temperature-ranges:
        - 298.14996337890625
        - 6000
      data:
        -
          - 20.972309112548828
          - -0.23713245391845705
          - 0.078406262397766116
          - 0
          - 0.090666691539809108
          - 243.23701078963279
          - 186.92131525503385
  - name: H2
    composition:
      H: 2
    thermo:
      model: Shomate
      temperature-ranges:
        - 298.14996337890625
        - 3000
        - 6000
      data:
        -
          - 28.874721527099609
          - -0.96402349472045901
          - 3.0446360778808592
          - -0.61167462158203123
          - 0.0065066444221884012
          - -8.5551219260245563
          - 165.75740457581296
        -
          - 36.061832427978516
          - 1.1070894241333009
          - 0
          - 0
          - -21.584697067737579
          - -31.661421592712401
          - 158.62969665521902
  - name: Sb2O3(c)
    composition:
      O: 3
      Sb: 2
    thermo:
      model: Shomate
      temperature-ranges:
        - 298.14996337890625
        - 879
        - 928
        - 6000
      data:
        -
          - 118.24195861816406
          - -8.1799987792968754
          - 35.320986328124995
          - -0
          - -1.274899672716856
          - -748.02616716384887
          - 266.68947361685753
        -
          - 125.56196594238281
          - -8.1799987792968754
          - 35.320986328124995
          - -0
          - -1.274899672716856
          - -740.05019546508788
          - 284.02700823673854
        -
          - 179.99996948242188
          - -0
          - -0
          - -0
          - -0
          - -729.30781693220138
          - 354.64257213390783
```

The Cantera works correctly if I remove node "Sb2O3(c)". The error occurs when adding species to the phase (in the cycle "for") and the Cantera doesn't display the error text.
