### ISSUE TITLE
Allow for alternative inherited YAML reaction definition

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1028]
**Problem description** / **Steps to reproduce**

The indenting of the `reaction` field for 'inherited' reactions is somewhat non-intuitive. While this works:

```yaml
phases:
- name: gas
  species:
  - h2o2.yaml/species: [H, O2, H2O, HO2]
  thermo: ideal-gas
  kinetics: gas
  reactions:
  - h2o2.yaml/reactions: declared-species
```

the more intuitive version (with reactions indented as in other YAML files) would be

```yaml
phases:
- name: gas
  species:
  - h2o2.yaml/species: [H, O2, H2O, HO2]
  thermo: ideal-gas
  kinetics: gas
reactions:
- h2o2.yaml/reactions: declared-species
```

which, however, throws an error

```
***********************************************************************
InputFileError thrown by AnyMap::operator[]:
Error on line XY of input string:
Key 'equation' not found.
Existing keys: h2o2.yaml/reactions
|  Line |
|     4 |       species:
|     5 |       - h2o2.yaml/species: [H, O2, H2O, HO2]
|     6 |       thermo: ideal-gas
|     7 |       kinetics: gas
|     8 |     reactions:
>     9 >     - h2o2.yaml/reactions: declared-species
                ^
|    10 |     
***********************************************************************
```

The error does point out the issue, but as there never was an intent to provide an equation, it is not necessarily intuitive.

**System information**

- Cantera version: 2.6.0a2
