### ISSUE TITLE
Two-temperature-plasma incompatible with third-body notation

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1220]
**Problem description**

Per #967/#1015/#1027 the following reaction in `test/data/ET_test.yaml`

```yaml
- equation: E + O2 + O2 => O2^- + O2  # Kossyi (1992) Eq.45
  type: two-temperature-plasma
  rate-constant: {A: 1.523e+27, b: -1.0, Ea_T: -100, Ea_Te: 700}
```

is a three-body reaction, but is currently not handled as such.

**Steps to reproduce**

Found in #1219

**Behavior**

Reaction was found using a generic search for implicitly defined third-body colliders

**System information**

- Cantera version: [for example, 2.5.0 or the git commit hash] 2.6.0a4
- OS: [for example, Windows 10]
- Python/MATLAB/other software versions:
