### ISSUE TITLE
Incorrect temperature ranges in nasa_condensed data

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#1245]
**Problem description**

Some of the species in the `nasa_condensed.yaml` file specify temperature ranges for the NASA polynomials that are not monotonically increasing, leading to some unexpected results.

**Steps to reproduce**
For example:
```yaml
- name: Fe(c)
  composition: {Fe: 1}
  thermo:
    model: NASA7
    temperature-ranges: [1000.0, 1665.0, 1000.0]
    data:
    - [61.010999, -0.160945061, 1.68369493e-04, -7.74563702e-08, 1.3309129e-11,
      -1.65335454e+04, -313.710668]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
Consistent with such a definition, the species reports that both the min and max temperature for the phase is 1000 K. The first polynomial is used below the "middle" temperature, and the second polynomial is used above.
```py
>>> Y = {s.name: s for s in ct.Species.list_from_file("nasa_condensed.yaml")}
>>> Y["Fe(c)"].thermo.min_temp
1000.0
>>> Y["Fe(c)"].thermo.max_temp
1000.0
>>> Y["Fe(c)"].thermo.cp(900)
39960.63009984842
>>> Y["Fe(c)"].thermo.cp(1100)
34006.03123840939
>>> Y["Fe(c)"].thermo.cp(1700)
0.0
```
This error in the temperature ranges is a result of strange temperature ranges being specified in the `nasa_condensed.cti` file:
```py
species(name = "Fe(c)",
    atoms = " Fe:1 ",
    thermo = (
       NASA( [ 1184.00,  1000.00], [  0.000000000E+00,   0.000000000E+00, 
                0.000000000E+00,   0.000000000E+00,   0.000000000E+00,
                0.000000000E+00,   0.000000000E+00] ),
       NASA( [ 1000.00,  1665.00], [  6.101099900E+01,  -1.609450610E-01, 
                1.683694930E-04,  -7.745637020E-08,   1.330912900E-11,
               -1.653354540E+04,  -3.137106680E+02] )
             )
    # note = "J 3/78"
       )
```
However, the behavior is slightly different:
```py
>>> C = {s.name: s for s in ct.Species.listFromFile("nasa_condensed.cti")}
>>> C["Fe(c)"].thermo.min_temp
1184.0
>>> C["Fe(c)"].thermo.max_temp
1665.0
>>> C["Fe(c)"].thermo.cp(900)
0.0
>>> C["Fe(c)"].thermo.cp(1100)
34006.03123840939
>>> C["Fe(c)"].thermo.cp(1200)
33941.28191262115
>>> C["Fe(c)"].thermo.cp(1300)
34649.86510008518
>>> C["Fe(c)"].thermo.cp(1800)
40037.53067186088
```
Based on files that were present in the repo at the time this file was originally introduced, it appears to have been generated from a CK-format input that specified the species as:
```
THERMO NO_TMID
 300.0   1000.0   5000.0
...
Fe(c)             J 3/78FE 1.   0.   0.   0.C  1184.000  1665.000     55.84700 1
 6.10109990E+01-1.60945061E-01 1.68369493E-04-7.74563702E-08 1.33091290E-11    2
-1.65335454E+04-3.13710668E+02 0.00000000E+00 0.00000000E+00 0.00000000E+00    3
 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00    4
```

Besides the "NO_TMID" declaration, which I've never seen before, this file is identical to the one hosted by Caltech's Explosion Dynamics Laboratory at https://shepherd.caltech.edu/EDL/PublicResources/sdt/SDToolbox/cti/NASA7/nasa7.dat.

I don't know that there's ever been a version of `ck2cti` that can handle this format where the last value in the first line is the molecular weight rather than the mid temperature. `ck2yaml` somewhat predictably writes this value as the mid temperature, e.g.:
```yaml
- name: Fe(c)
  composition: {Fe: 1}
  thermo:
    model: NASA7
    temperature-ranges: [1184.0, 55.84, 1665.0]
    data:
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [61.010999, -0.160945061, 1.68369493e-04, -7.74563702e-08, 1.3309129e-11,
      -1.65335454e+04, -313.710668]
    note: J3/78
```
Interestingly, the EDL page also has another file, https://shepherd.caltech.edu/EDL/PublicResources/sdt/SDToolbox/cti/NASA7/nasa7mod.dat, where the mid temperature has been inserted for each species, except for those where there is only one valid temperature range, and the description specifically says that it is "useful for generating Cantera .cti files by converting Chemkin-style input files". In this file, the entry for `Fe(c)` looks like:
```
Fe(c)             J 3/78FE  1    0    0    0S  1184.000  1665.000              1  
 6.10109990E+01-1.60945061E-01 1.68369493E-04-7.74563702E-08 1.33091290E-11    2
-1.65335454E+04-3.13710668E+02 0.00000000E+00 0.00000000E+00 0.00000000E+00    3
 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00 0.00000000E+00    4
```

Of course, this has several formatting errors that have to be corrected before `ck2yaml` is happy, at which point we end up with:
```yaml
- name: Fe(c)
  composition: {Fe: 1}
  thermo:
    model: NASA7
    temperature-ranges: [1184.0, 1000.0, 1665.0]
    data:
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [61.010999, -0.160945061, 1.68369493e-04, -7.74563702e-08, 1.3309129e-11,
      -1.65335454e+04, -313.710668]
    note: J3/78
```
which doesn't seem quite right, either.

**System information**

- Cantera version: 2.6.0b2 / e7b931b2a
