### ISSUE TITLE
UnitSystem::convert should raise InputFileError where possible

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#1283]
**Problem description**

Incorrect units specified in YAML input files result in error messages that aren't easy to trace back to the problematic input data.

**Steps to reproduce**

Importing the following YAML file:
```yaml
phases:
- name: gas
  thermo: ideal-gas
  species: [{h2o2.yaml/species: all}]
  kinetics: gas
  reactions: all

reactions:
- equation: O + H2 <=> H + OH  # Reaction 3
  rate-constant: {A: 3.87e+04 cm^6/mol^2/s, b: 2.7, Ea: 6260.0}
```

produces the error message:
```
CanteraError: 
*******************************************************************************
CanteraError thrown by addReactions:

*******************************************************************************
CanteraError thrown by UnitSystem::convert:
Incompatible units:
    Units(1.0000000000000002e-06 m^6 / kmol^2 / s) and
    Units(m^3 / kmol / s)
*******************************************************************************
*******************************************************************************
```

Which doesn't tell the user which reaction was the source of the problem. Raising an `InputFileError` would be a nice improvement, though it will require some changes to how this is handled in the `UnitSystem` class.

**System information**

- Cantera version: 2.6.0
