### ISSUE TITLE
Duplicate reaction not found when marked properly

### ISSUE THREAD

**Issue by corykinney** [Cantera/cantera#1353]
**Problem description**

Cantera is giving the following error when loading a mechanism that was converted using `ck2yaml`:

```
No duplicate found for declared duplicate reaction number 283 (C2H3 + CH2O <=> C2H4 + HCO)
```

The relevant reaction and its duplicate are both marked with `duplicate: true` and have the exact same species order.

```yaml
- equation: C2H3 + CH2O <=> C2H4 + HCO  # Reaction 284
  duplicate: true
  type: pressure-dependent-Arrhenius
  rate-constants:
  - {P: 0.001 atm, A: 1.1e+07, b: 1.09, Ea: 1807.0}
  - {P: 0.01 atm, A: 2.5e+07, b: 0.993, Ea: 1995.0}
  - {P: 0.1 atm, A: 2.5e+08, b: 0.704, Ea: 2596.0}
  - {P: 1.0 atm, A: 1.4e+10, b: 0.209, Ea: 3934.0}
  - {P: 10.0 atm, A: 3.5e+13, b: -0.726, Ea: 6944.0}
  - {P: 100.0 atm, A: 3.3e+14, b: -0.866, Ea: 1.0966e+04}
  - {P: 1000.0 atm, A: 17.0, b: 3.17, Ea: 9400.0}
- equation: C2H3 + CH2O <=> C2H4 + HCO  # Reaction 285
  duplicate: true
  type: pressure-dependent-Arrhenius
  rate-constants:
  - {P: 0.001 atm, A: -2.3e+16, b: -1.269, Ea: 2.0617e+04}
  - {P: 0.01 atm, A: -5.2e+16, b: -1.366, Ea: 2.0805e+04}
  - {P: 0.1 atm, A: -1.5e+18, b: -1.769, Ea: 2.2524e+04}
  - {P: 1.0 atm, A: -8.5e+19, b: -2.264, Ea: 2.3862e+04}
  - {P: 10.0 atm, A: -4.4e+23, b: -3.278, Ea: 2.7795e+04}
  - {P: 100.0 atm, A: -4.2e+24, b: -3.418, Ea: 3.1817e+04}
  - {P: 1000.0 atm, A: -2.1e+11, b: 0.618, Ea: 3.0251e+04}
```

so it is not clear to me why the duplicate is not being found by `Kinetics::checkDuplicates`. 

**System information**

- Cantera version: 2.6.0
- OS: Windows 11
- Python: 3.8

**Comment by ischoegl** [comment]
@cory-kinney … thanks for the report. Could you provide the input data (or a minimal example) to facilitate?

**Comment by corykinney** [comment]
@ischoegl Attached is a [minimal example](https://github.com/Cantera/cantera/files/9261747/test.yaml.txt) for those two reactions, I had to make it a `.txt` since it seems GitHub doesn't allow `.yaml` files.

**Comment by ischoegl** [comment]
Hi @cory-kinney ... I can confirm that the problem still exists with 3.0.0a2. As a short-term work-around, you should be able to import if you remove the `duplicate` field to proceed.

**Comment by corykinney** [comment]
> Hi @cory-kinney ... I can confirm that the problem still exists with 3.0.0a2. As a short-term work-around, you should be able to import if you remove the `duplicate` field to proceed.

I did attempt the workaround when I first encountered the issue, but then I received the following error:

```
CanteraError thrown by PlogRate::validate:
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 101.33, T = 200.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 101.33, T = 500.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 101.33, T = 1000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 101.33, T = 2000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 101.33, T = 5000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 101.33, T = 10000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1013.3, T = 200.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1013.3, T = 500.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1013.3, T = 1000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1013.3, T = 2000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1013.3, T = 5000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1013.3, T = 10000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 10133, T = 200.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 10133, T = 500.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 10133, T = 1000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 10133, T = 2000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 10133, T = 5000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 10133, T = 10000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+05, T = 200.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+05, T = 500.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+05, T = 1000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+05, T = 2000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+05, T = 5000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+05, T = 10000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+06, T = 200.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+06, T = 500.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+06, T = 1000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+06, T = 2000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+06, T = 5000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+06, T = 10000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+07, T = 200.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+07, T = 500.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+07, T = 1000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+07, T = 2000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+07, T = 5000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+07, T = 10000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+08, T = 200.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+08, T = 500.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+08, T = 1000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+08, T = 2000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+08, T = 5000.0
Invalid rate coefficient for reaction 'C2H3 + CH2O <=> C2H4 + HCO'
at P = 1.0132e+08, T = 10000.0
```

I'm not sure if this is related or if it's an issue with the reaction rates themselves.

**Comment by ischoegl** [comment]
@cory-kinney ... I saw this also, but from my perspective, this is an unrelated bug. 

Does the mechanism import correctly via the legacy CTI/XML route?

**Comment by speth** [comment]
The incorrect error message seen here is caused by the problem indicated in the second error message, obtained without marking the reaction as duplicate. I've pushed a fix in #1356 that will cause the correct error message to be shown.

The underlying problem comes down to a misunderstanding as to how PLOG rates with multiple rates at a single pressure are supposed to be written, for use with either Cantera or Chemkin. In both cases, they should be written as a **single reaction** with all rate constants listed, for example:
```yaml
  - equation: C2H3 + CH2O <=> C2H4 + HCO
    type: pressure-dependent-Arrhenius
    rate-constants:
    - {P: 0.001 atm, A: 1.1e+07, b: 1.09, Ea: 1807.0}
    - {P: 0.001 atm, A: -2.3e+16, b: -1.269, Ea: 2.0617e+04}
    - {P: 0.01 atm, A: 2.5e+07, b: 0.993, Ea: 1995.0}
    - {P: 0.01 atm, A: -5.2e+16, b: -1.366, Ea: 2.0805e+04}
    - {P: 0.1 atm, A: 2.5e+08, b: 0.704, Ea: 2596.0}
    - {P: 0.1 atm, A: -1.5e+18, b: -1.769, Ea: 2.2524e+04}
    - {P: 1.0 atm, A: 1.4e+10, b: 0.209, Ea: 3934.0}
    - {P: 1.0 atm, A: -8.5e+19, b: -2.264, Ea: 2.3862e+04}
    - {P: 10.0 atm, A: -4.4e+23, b: -3.278, Ea: 2.7795e+04}
    - {P: 10.0 atm, A: 3.5e+13, b: -0.726, Ea: 6944.0}
    - {P: 100.0 atm, A: 3.3e+14, b: -0.866, Ea: 1.0966e+04}
    - {P: 100.0 atm, A: -4.2e+24, b: -3.418, Ea: 3.1817e+04}
    - {P: 1000.0 atm, A: 17.0, b: 3.17, Ea: 9400.0}
    - {P: 1000.0 atm, A: -2.1e+11, b: 0.618, Ea: 3.0251e+04}
```
This way, all the rates at a given pressure can be added together before doing the logarithmic interpolation. Otherwise, with negative pre-exponential factors, the interpolation is impossible.
