### ISSUE TITLE
Validation for PLOG rates fails for extremely high pre-exponential factors after Cantera 2.6 release

### ISSUE THREAD

**Issue by corykinney** [Cantera/cantera#1405]
**Problem description**

The AramcoMech 3.0 mechanism (and NUIGMech 1.1, which containts the same problematic reactions) fails to validate after Cantera 2.6.0 was released. This reaction mechanism did not cause issues with Cantera 2.5; this behavior specifically started occurring between 2.6.0a4 and 2.6.0b2. 

**Steps to reproduce**

1. Download the CHEMKIN files for AramcoMech 3.0 from [NUI Galway](https://c3.universityofgalway.ie/combustionchemistrycentre/mechanismdownloads/)
2. Convert these files to Cantera format with `ck2yaml`
3. See error

```
CanteraError thrown by PlogRate::validate:
Invalid rate coefficient for reaction 'C4H6 <=> C3H3 + CH3'
at P = 15999, T = 200.0
Invalid rate coefficient for reaction 'C4H6 <=> C3H3 + CH3'
at P = 31997, T = 200.0
```

the reaction that is causing this error is:

```yaml
- equation: C4H6 <=> CH3 + C3H3  # Reaction 2176
  type: pressure-dependent-Arrhenius
  rate-constants:
  - {P: 0.0394737 atm, A: 1.5849e+148, b: -37.24, Ea: 1.885e+05}
  - {P: 0.0789474 atm, A: 8.9125e+159, b: -40.32, Ea: 2.013e+05}
  - {P: 0.157895 atm, A: 5.2481e+196, b: -50.0, Ea: 2.436e+05}
  - {P: 0.315789 atm, A: 4.0738e+196, b: -50.0, Ea: 2.414e+05}
```

The pre-exponential factors are absurdly high, of course, which was discussed in the [Cantera Google group discussion](https://groups.google.com/g/cantera-users/c/nrB3E24hTOI) as a potential cause of the issue. As suggested by @bryanwweber I calculated the corresponding reaction rates, and the rates should be positive, although they are smaller than `1e-100` if I recall correctly. It's possible that I calculated them incorrectly, but otherwise I do not see why Cantera should fail to validate the mechanism. Perhaps there is a precision error where the reaction rate is truncated and becomes zero, which might fail the validation?

**System information**

- Cantera version: 2.6.0
- Python version: 3.10

**Comment by ischoegl** [comment]
@cory-kinney ... thanks for reporting this issue. For context, the offending code section where this fails is https://github.com/Cantera/cantera/blob/577455cf143178407729f1fdcb9085570dc84b3d/src/kinetics/PlogRate.cpp#L146-L153

**Comment by corykinney** [comment]
@ischoegl would it be appropriate to change this to `!(k >= 0)` (or just `k < 0`) to allow for rates that might truncate to zero but still disallow negative rates?

**Comment by ischoegl** [comment]
@cory-kinney … Interesting question. However, the log of a number that gets truncated to zero is still problematic? (I’m actually not sure why `k=0` is allowed in this validation check).

**Comment by corykinney** [comment]
@ischoegl `k=0` is not allowed in the code section you linked. I'm not entirely sure if the rate is calculated as zero or if it's calculating a negative rate.

Regardless, is there a way to override these checks that are saying the mechanism would fail at 200 K when that is irrelevant to the simulation that will be run? I know this has been discussed in https://github.com/Cantera/enhancements/issues/54 but it doesn't look like there was a resolution. 

Widely used mechanisms such as AramcoMech 3.0 and others from NUI Galway are no longer usable with releases after 2.6.0a4 due to these checks when most of the time it wouldn't matter. It would be great if there was a flag or something to make these appear as warnings instead of exceptions so that the user is aware of the issue but isn't unnecessarily restricted by Cantera.

**Comment by corykinney** [comment]
Also tagging @bryanwweber since he was involved in the original discussion on the Google group.

**Comment by ischoegl** [comment]
I looked at the commit history, and the check goes back at least 8 years (50a08db7c09f9a4cdb0c3598b42818c4717b265c), with a more recent change to improve output in 2cd06194e80aa0f43cba36575ecf1cdc6c073391 ... the current version of the code is the result of refactoring of reaction rate evaluators, which involved copying things around. I am actually not sure why checks pass prior to 2.6 - it's certainly not because of changes in this section.

For the original code conversion, you can pass the `--no-validate` option to `ck2yaml`, but I'm not sure that this resolves your issues.

**Comment by corykinney** [comment]
> I looked at the commit history, and the check goes back at least 8 years ([50a08db](https://github.com/Cantera/cantera/commit/50a08db7c09f9a4cdb0c3598b42818c4717b265c)), with a more recent change to improve output in [2cd0619](https://github.com/Cantera/cantera/commit/2cd06194e80aa0f43cba36575ecf1cdc6c073391) ... the current version of the code is the result of refactoring of reaction rate evaluators, which involved copying things around. I am actually not sure why checks pass prior to 2.6 - it's certainly not because of changes in this section.
> 
> For the original code conversion, you can pass the `--no-validate` option to `ck2yaml`, but I'm not sure that this resolves your issues.

Unfortunately passing `--no-validate` to `ck2yaml` might prevent the issue when converting the mechanisms, but anytime the mechanism is loaded with `ct.Solution(...)` the checks occur again and prevent them from being used.

In the original commit the check is `if (!(k >= 0))` versus the current `if (!(k > 0))`. I just checked the blame for the current version of the file and it looks like this change was made in [`9b4f4de`](https://github.com/Cantera/cantera/commit/9b4f4de3cbe421ee29e6db38c4f79a19ae2884db) which ended up in 2.6.0b1 (which makes sense as to why 2.6.0a4 is the last `pip` installable release that I can successfully use these mechanisms with). It looks like @speth made the change. Is there a reason why `k = 0` was considered valid until recently and is now disallowed?

**Comment by ischoegl** [comment]
Thanks for pointing out the slightly different conditions (which essentially is `k <= 0`  in its current form). Blocking `k == 0` makes sense mathematically as a logarithm would create issues; in this case, it may be that a positive value is rounded to zero due to limited machine precision. Fwiw, here's the rate evaluation step:
```C++
    //! Evaluate reaction rate
    double evalRate(double logT, double recipT) const {
        return m_A * std::exp(m_b * logT - m_Ea_R * recipT);
    }
```
It should be easily verifiable whether the exponential becomes exceedingly small? 
```YAML
- equation: C4H6 <=> CH3 + C3H3  # Reaction 2176
  type: pressure-dependent-Arrhenius
  rate-constants:
  - {P: 0.0394737 atm, A: 1.5849e+148, b: -37.24, Ea: 1.885e+05}
  - {P: 0.0789474 atm, A: 8.9125e+159, b: -40.32, Ea: 2.013e+05}
  - {P: 0.157895 atm, A: 5.2481e+196, b: -50.0, Ea: 2.436e+05}
  - {P: 0.315789 atm, A: 4.0738e+196, b: -50.0, Ea: 2.414e+05}
```
It doesn't look like the pre-exponential factors are at fault - they are clearly positive. Whether those numbers makes actual physical sense is beyond me ...

**Comment by speth** [comment]
Allowing $k=0$ causes the interpolation formula for these rates to return NaN, since $\infty - \infty$ is not defined. I think the validation check here should have _always_ failed when $k$ evaluates to exactly zero.

For debugging purposes, you can get a better picture of what's happening here by creating a few elementary reactions with these rate constants (where zeros aren't a problem), and including just these few reactions in the input file:
```yaml
reactions:
- equation: C4H6 <=> CH3 + C3H3  # Reaction 2176
  rate-constant: {A: 1.5849e+148, b: -37.24, Ea: 1.885e+05}
  duplicate: true
- equation: C4H6 <=> CH3 + C3H3  # Reaction 2176
  rate-constant: {A: 8.9125e+159, b: -40.32, Ea: 2.013e+05}
  duplicate: true
- equation: C4H6 <=> CH3 + C3H3  # Reaction 2176
  rate-constant: {A: 5.2481e+196, b: -50.0, Ea: 2.436e+05}
  duplicate: true
- equation: C4H6 <=> CH3 + C3H3  # Reaction 2176
  rate-constant: {A: 4.0738e+196, b: -50.0, Ea: 2.414e+05}
  duplicate: true
```
This way, we can actually import the mechanism and play around with it a little.
```python
>>> import cantera as ct
>>> import numpy as np
>>> gas = ct.Solution("pdep-parts.yaml")
>>> gas.TP = 300, ct.one_atm
>>> print(gas.forward_rate_constants)
array([4.29145770e-082, 2.68202286e-087, 2.54109265e-105, 7.90105084e-104])
>>> gas.TP = 260, ct.one_atm
>>> print(gas.forward_rate_constants)
>>> array([6.62111473e-101, 2.36401075e-107, 0.00000000e+000, 0.00000000e+000])
```
As you can see, below this temperature, the rate evaluates to exactly zero, as a result of floating point underflow. While at first glance it might seem that we should still be pretty far from the limit of the smallest values representable in a double (around 1e-300), the problem comes from the fact that the intermediate result, equivalent to evaluating $T^b \exp(E_a/RT)$ falls below this limit:
```python
>>> rate = gas.reaction(2).rate
>>> T = 260
>>> print(T**rate.temperature_exponent)
1.7837443128686528e-121
>>> print(np.exp(-rate.activation_energy / (ct.gas_constant*T)))
1.7366368018543418e-205
>>> print(T**rate.temperature_exponent * np.exp(-rate.activation_energy / (ct.gas_constant*T)))
0.0
```
I think the best way to handle this would be to implement controllable temperature bounds for `Kinetics` calculations, where the bounds could be determined in part by automatically identifying the range over which the rate constants are mathematically/numerically valid.

A simpler band-aid for the 2.6 branch might be to just increase the lowest validation temperature to 300 K, which seems to be fine for AramcoMech 3.0.
