### ISSUE TITLE
Segfault with undefined/explicit third-body collider

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1587]
**Problem description**

Reactions with explicit third body colliders that are undefined are not caught.

**Steps to reproduce**

Load minimal YAML 

```yaml
generator: YamlWriter
cantera-version: 3.0.0b1
git-commit: 4b30fa74b
date: Sat Aug 12 07:34:23 2023
phases:
  - kinetics: gas
    name: ""
    skip-undeclared-third-bodies: true
    thermo: ideal-gas
    elements: [H, O, Ar, N]
    species:
    - gri30.yaml/species: [H2, H, O, O2, OH, H2O, HO2, H2O2, AR, N2]
    state:
      T: 1.0e-03
      density: 1.0e-03
      Y: {H2: 1.0}
reactions:
  - equation: 2 H + CO2 <=> H2 + CO2
    rate-constant: {A: 5.5e+14, b: -2.0, Ea: 0.0}
```

**Behavior**

Reaction should be skipped (`CO2` is not among species, and `skip-undeclared-third-bodies` is set), but causes segfault instead.

**System information**

- Cantera version: main
- OS: macOS
- Python/MATLAB/other software versions: N/A

**Additional context**

Input file is based on output produced for an attempted fix for #1403 (the 'workaround' therein produces the segfault as well)
