### ISSUE TITLE
Build from source on Power PC 9: linking problem and segmentation error

### ISSUE THREAD

**Issue by CharlelieLrt** [Cantera/cantera#1627]
**Problem description**

Cannot build cantera from source on Power PC 9 architecture using either conda or cantera's submodules. Getting either an undefined symbol from a linked library, or a segmentation error.

**Steps to reproduce**

I am attempting to build cantera from source on a power PC 9 system. I am working in a conda environment, created with the following config:

```yaml
name: ct-env
channels:
  - defaults
  - conda-forge
dependencies:
- python  # Cantera supports Python 3.8 and up
- scons  # build system
- boost-cpp  # C++ dependency
- hdf5  # optional C++ dependency
- highfive  # C++ dependency; uncomment to override Cantera default
- sundials  # uncomment to override Cantera default
- fmt  # uncomment to override Cantera default
- eigen  # uncomment to override Cantera default
- yaml-cpp  # uncomment to override Cantera default
- libgomp  # optional (OpenMP implementation when using GCC)
- cython  # needed to build Python package
- numpy  # needed to build Python package
- pip  # needed to build Python package
- wheel  # needed to build Python package
- setuptools  # needed to build Python package
- pytest  # needed for the Python test suite
- ruamel.yaml  # needed for converter scripts
- scipy  # optional (needed for some examples)
- matplotlib  # optional (needed for plots)
```

Cantera 3.0 is built from source using the following scons config:

```python
f90_interface = 'n'
system_eigen = 'y'
system_fmt = 'y'
hdf_support = 'n'
system_highfive = 'y'
system_yamlcpp = 'y'
system_sundials = 'y'
system_blas_lapack = 'y'
extra_lib_dirs = '$CONDA_PREFIX/lib'
```

Note that this is using conda's provided packages for yaml-cpp, fmt, eigen, sundials, blas and lapack.

After the built completes, running `import cantera` in python gives an undefined symbol error related to `YAML::Emitter::Write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)` from the library `.conda/envs/kinetics/lib/libyaml-cpp.so.0.7`. I checked and this version of yaml-cpp (v0.7) does not define this symbol. Older versions of yam-cpp (e.g. v5.0) do define the missing symbol.

I therefore decided to use cantera's Git submodule for yaml-cpp, instead of the one provided by conda.
After doing so, I am getting a new undefined symbol, but this time related to the symbol `fmt::v9::vformat(fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)` from the library `.conda/envs/kinetics/lib/libfmt.so.9`. Once again I checked  and fmt-cpp v9 does not define this symbol.

So I once again decided to use cantera's submodule for `fmt-cpp` instead of the one provided by conda. After rebuilding cantera, I am able to run `import cantera` from a python script. However, running a python test gives me a segmentation error:

```
0x0000200815c3e10c in std::vector<std::filesystem::path::_Cmpt, std::allocator<std::filesystem::path::_Cmpt> >::~vector (this=0x38, __in_chrg=<optimized out>)
    at /usr/tce/packages/gcc/gcc-8.3.1/rh/usr/include/c++/8/bits/stl_vector.h:565
565	      ~vector() _GLIBCXX_NOEXCEPT
``` 

**System information**

- Cantera version: 3.0, built from source
- Compiler: gcc 8.3.1
- OS: RHEL 7.9
- Architecture: Power PC9
- Python/MATLAB/other software versions: Reproduced with Python 3.8.1 and 3.11.5
