### ISSUE TITLE
Two-point control experiences converges issue at higher pressures

### ISSUE THREAD

**Issue by wandadars** [Cantera/cantera#1747]
**Problem description**

The nature of the issue is described [here](https://groups.google.com/g/cantera-users/c/_eoFn5FkT4A/m/Wvy5zNc9AQAJ?utm_medium=email&utm_source=footer)

There seems to be an issue with the handling of the boundary conditions when the two-point flame control is activated that results in a negative left inlet velocity at higher pressures.

An example highlighting the issue is below.

```
from pathlib import Path
import cantera as ct
import numpy as np
import matplotlib.pyplot as plt


p = 5.6e6 # pressure [Pascals]
#p = 101325 # pressure [Pascals]

fuel_inlet_temp= 800.0  # fuel inlet temperature [Kelvin]
oxidizer_inlet_temp= 711.0  # oxidizer inlet temperature [Kelvin]
fuel_mdot= 0.1 # kg/m^2/s
width= 50.0e-3 # Distance between inlets [m]


oxidizer_composition= 'O2:1.0'  # oxidizer composition (right)
fuel_composition= 'H2:1.0'  # fuel composition (left)


# Reaction mechanism
mechanism= 'h2o2.yaml'

# Define output locations
output_path = Path() / "testing_output"
output_path.mkdir(parents=True, exist_ok=True)

gas = ct.Solution(mechanism)


gas.TPY = fuel_inlet_temp, p, oxidizer_composition
density_f = gas.density


gas.TPY = oxidizer_inlet_temp, p, oxidizer_composition
density_o = gas.density


#Unity Lewis number testing
gas.transport_model = 'unity-Lewis-number'

f = ct.CounterflowDiffusionFlame(gas, width=width)
f.set_refine_criteria(ratio=15, slope= 0.25, curve= 0.08, prune= 0.04)

#Set the state of the two inlets
f.fuel_inlet.mdot = fuel_mdot
f.fuel_inlet.X = fuel_composition
f.fuel_inlet.T = fuel_inlet_temp



#Create a guestimate for what the oxidizer mdot would be
f.oxidizer_inlet.mdot = (fuel_mdot / density_f) * density_o 
f.oxidizer_inlet.X = oxidizer_composition
f.oxidizer_inlet.T = oxidizer_inlet_temp



# Generate initial condition
f.solve(auto=True)


#Loop until extinction
for i in range(100):
    new_fuel_mdot = 1.1*f.fuel_inlet.mdot
    new_oxidizer_mdot = 1.1*f.oxidizer_inlet.mdot
    f.fuel_inlet.mdot = new_fuel_mdot
    f.oxidizer_inlet.mdot = new_oxidizer_mdot

    try:
        f.solve()
    except ct.CanteraError as e:
        print('Solver did not converge. Stopping.')
        break

print('Strain mode completed')

print('Max T:')
print(max(f.T))

f.two_point_control_enabled = True

spacing = 0.85
temperature_increment = 5 # Kelvin
maximum_temperature = []
a_max = []

for i in range(5000):
    control_temperature = np.min(f.T) + spacing*(np.max(f.T) - np.min(f.T))

    print(f'Iteration {i}: Control temperature = {control_temperature} K')
    f.set_left_control_point(control_temperature)
    f.set_right_control_point(control_temperature)


    # This decrement is what drives the two-point control. If failure
    # occurs, try decreasing the decrement.
    f.left_control_point_temperature -= temperature_increment
    f.right_control_point_temperature -= temperature_increment


    try:
        f.solve(loglevel=2,refine_grid=False)
    except ct.CanteraError as e:
        print('Solver did not converge. Stopping.')
        break

    maximum_temperature.append(np.max(f.T))
    a_max.append(np.max(np.abs(np.gradient(f.velocity) / np.gradient(f.grid))))



# Plot the maximum temperature versus the maximum axial velocity gradient
plt.figure()
plt.plot(a_max, maximum_temperature)
plt.xlabel('Maximum Axial Velocity Gradient [1/s]')
plt.ylabel('Maximum Temperature [K]')
plt.savefig(output_path / "figure_max_temperature_vs_max_velocity_gradient.png")





# Plot maximum_temperature against number of iterations
plt.figure()
plt.plot(range(len(maximum_temperature)), maximum_temperature)
plt.xlabel('Number of Continuation Steps')
plt.ylabel('Maximum Temperature [K]')
plt.savefig(output_path / "figure_max_temperature_iterations.png")



```

**Comment by wandadars** [comment]
Edit: I think this wasn't really a thing. Strangely, doing a f.save() with overwrite=True was not actually overwriting a solution YAML file that I was writing, so it was always holding a previous state in it.  I thought that the overwrite flag wouldn't overwrite the contents of a YAML file that already exists.


One thing I notice is that the value of m_mdot seems to be different between a steady-state solve with the two-point control off and the same condition with two-point control on.  I just activate the two-point control and provide no decrement from the control points, which should just keep the solution at the value it was previously.

Two-point control off:

```
  fuel_inlet:
    type: inlet
    size: 1
    points: 1
    mass-flux: 0.285311670611
    temperature: 800.0
    pressure: 1.01325e+05
    mass-fractions:
      H2: 1.0
  oxidizer_inlet:
    type: inlet
    size: 1
    points: 1
    mass-flux: 0.3210257897170186
    temperature: 711.0
    pressure: 1.01325e+05
    mass-fractions:
      O2: 1.0
```


In the two-point control solution output we have:

```
  fuel_inlet:
    size: 1
    type: inlet
    points: 1
    mass-flux: 0.09999672452275071
    temperature: 800.0
    pressure: 1.01325e+05
    mass-fractions:
      H2: 1.0

  oxidizer_inlet:
    type: inlet
    size: 1
    points: 1
    mass-flux: 0.4500576439314927
    temperature: 711.0
    pressure: 1.01325e+05
    mass-fractions:
      O2: 1.0

```

When I look at the initial solution, I see a U(0) and rho(0) as being the same as the solution at that location with the two-point control. The same is true for the right boundary values of U and rho(which should be the things contributing to the value of m_mdot).  Even with this equality between solutions, the m_mdot discrepancy is there however.
