### ISSUE TITLE
InterfaceKinetics::modifyReaction reports error when using Python Arrhenius rate

### ISSUE THREAD

**Issue by whj0924** [Cantera/cantera#1870]
Hi, all.
I am trying modify the reaction  and thermodynamic parameters in example.
The version I use is 3.1.0 in python.
 code:
```py
    for k in range(surf.n_reactions):
        if surf.reactant_stoich_coeff(idx, k) > 0:
            my_rxn = surf.reaction(k)
            newEa = oldEa[k] + change_in_activation_energy * surf.reactant_stoich_coeff(idx, k)
            new_rate = ct.Arrhenius(A=oldA[k], b=oldb[k], E=newEa)
            my_rxn.rate = new_rate
            surf.modify_reaction(k, my_rxn)
```
error: 
```
CanteraError thrown by InterfaceKinetics::modifyReaction: Interface evaluator not available for type 'custom-rate-function'.
```

My Input File：
```yaml
- equation: X(1) + X(1) + H2(3) <=> HX(5) + HX(5)  # Reaction 1
  sticking-coefficient: {A: 0.1, b: 0.0, Ea: 18.617}
- equation: X(1) + X(1) + C2H6(2) <=> HX(5) + C2H5X(4)  # Reaction 2
  sticking-coefficient: {A: 2.052, b: 0.0, Ea: 30.425}
- equation: X(1) + C2H6(2) <=> C2H6X(6)  # Reaction 3
  sticking-coefficient: {A: 1.0e-14, b: 0.0, Ea: 0.0}
- equation: X(1) + C2H6X(6) <=> HX(5) + C2H5X(4)  # Reaction 4
  rate-constant: {A: 4.14e+21, b: 0.0, Ea: 38.765}
- equation: X(1) + C2H5X(4) <=> HX(5) + C2H4X(10)  # Reaction 5
  rate-constant: {A: 4.179e+21, b: 0.0, Ea: 31.994}
- equation: C2H5X(4) + C2H5X(4) <=> C2H4X(10) + C2H6X(6)  # Reaction 6
  rate-constant: {A: 4.179e+21, b: 0.0, Ea: 6.442}
- equation: X(1) + C2H4(12) <=> C2H4X(10)  # Reaction 7
  sticking-coefficient: {A: 0.01, b: 0.0, Ea: 0.0}
- equation: X(1) + X(1) + C2H5X(4) <=> HX(5) + C2H4X2(11)  # Reaction 8
  rate-constant: {A: 4.23e+30, b: 0.0, Ea: 46.455}
```

Using the code with the previous version hasn't reported an error yet，How to change the code？
