### ISSUE TITLE
Unable to import all species containing C and S

### ISSUE THREAD

**Issue by Saintis** [Cantera/cantera#621]
### Cantera version
2.5.0a2 (848a3bf)
### Operating System
Ubuntu 18.04

### Python/MATLAB version
Python 3.6

### Expected Behavior
Able to import all species from `nasa` containing C and S.

### Actual Behavior
CanteraError thrown: "phase gas already contains a species named Cs".

### Steps to reproduce
Run
```
import cantera as ct

gas_cti = """ideal_gas(
    name="gas",
    elements=" S C ",
    species=" nasa: all ",
    options=["skip_undeclared_elements"],
    initial_state=state(temperature=300, pressure=(1, "bar"))
)"""
gas = ct.Solution(source=gas_cti)
```

Error:
```
Traceback (most recent call last):
  File "equilibrium_modelling.py", line 20, in <module>
    gas = ct.Solution(source=gas_cti)
  File "interfaces/cython/cantera/base.pyx", line 29, in cantera._cantera._SolutionBase.__cinit__
  File "interfaces/cython/cantera/base.pyx", line 65, in cantera._cantera._SolutionBase._init_cti_xml
cantera._cantera.CanteraError:
***********************************************************************
CanteraError thrown by Phase::addSpecies:
Phase 'reactor_gas' already contains a species named 'Cs'.
***********************************************************************
```

**Comment by bryanwweber** [comment]
Hi! Thank you for your patience waiting for a response to this issue.

This appears to be because the check for undeclared elements is done after reading the species, and/or because the species names are not treated as case sensitive. I'd have to look into the code a little more to exactly figure out why this is happening, but I can reproduce the problem. Thank you for reporting it!

**Comment by ischoegl** [comment]
Look like the string ` S  C ` gets sorted and is interpreted as Caesium `Cs`, which is present in nasa.cti (trying ` S  C ` and ` C  S ` gets identical results; good thing that it doesn't have Scandium ...). Tests with other non-standard elements '  Pb  C  ' etc. give  expected results. I.e. I don't think that the option "skip_undeclared_elements" is at fault here.

**Comment by ischoegl** [comment]
Looks like @bryanwweber's second suggestion is correct: it appears to be a case of the CTI parser not being case sensitive when it comes to species names. 

The following is a minimum cti file that reproduces the behavior. If one of the species `CS` or `Cs` is deleted, the import works.
```python
units(length = "cm", time = "s", quantity = "mol", act_energy = "cal/mol")


ideal_gas(name = "issue_621",
      elements = " S  C  Cs ",
      species = "all",
      reactions = "all",
      initial_state = state(temperature = 300.0,
                                      pressure = OneAtm)    )

species(name = "S",
    atoms = " S:1 ",
    thermo = (
       NASA( [  200.00,  1000.00], [  2.317256160E+00,   4.780183420E-03,
               -1.420826740E-05,   1.565695380E-08,  -5.965882990E-12,
                3.250689760E+04,   6.062424340E+00] ),
       NASA( [ 1000.00,  6000.00], [  2.879364980E+00,  -5.110503880E-04,
                2.538067190E-07,  -4.454554580E-11,   2.667173620E-15,
                3.250137910E+04,   3.981406470E+00] )
             )
    # note = "J 9/82"
       )

species(name = "C",
    atoms = " C:1 ",
    thermo = (
       NASA( [  200.00,  1000.00], [  2.554239550E+00,  -3.215377240E-04,
                7.337922450E-07,  -7.322348890E-10,   2.665214460E-13,
                8.544388320E+04,   4.531308480E+00] ),
       NASA( [ 1000.00,  6000.00], [  2.605582980E+00,  -1.959343350E-04,
                1.067372190E-07,  -1.642393900E-11,   8.187057520E-16,
                8.541294430E+04,   4.192386810E+00] )
             )
    # note = "L11/88"
       )

species(name = "CS",
    atoms = " C:1  S:1 ",
    thermo = (
       NASA( [  300.00,  1000.00], [  3.403934400E+00,  -6.577330800E-04,
                6.171215700E-06,  -7.368960400E-09,   2.734673800E-12,
                3.268939300E+04,   5.911067290E+00] ),
       NASA( [ 1000.00,  5000.00], [  3.682601200E+00,   9.047320300E-04,
               -3.643637400E-07,   6.385429400E-11,  -3.693398200E-15,
                3.249749000E+04,   3.898416790E+00] )
             )
    # note = "J12/76"
       )

species(name = "Cs",
    atoms = " Cs:1 ",
    thermo = (
       NASA( [  200.00,  1000.00], [  2.500045540E+00,  -4.668333560E-07,
                1.680050610E-09,  -2.482180290E-12,   1.277121900E-15,
                8.455404360E+03,   6.875735390E+00] ),
       NASA( [ 1000.00,  6000.00], [  2.820233150E+00,  -3.348403270E-04,
               -9.829157090E-08,   1.275643690E-10,  -1.461192710E-14,
                8.306393540E+03,   5.008940420E+00] )
             )
    # note = "L 3/93"
       )
```

**Comment by ischoegl** [comment]
FYI: the new yaml parser raises the same exception with the following input:
```yaml
phases:
- name: gas
  thermo: ideal-gas
  elements: [S, C, Cs]
  state: {T: 300.0, P: 1 atm}

species:
- name: C
  composition: {C: 1}
  thermo:
    model: NASA7
    temperature-ranges: [200.0, 1000.0, 6000.0]
    data:
    - [2.55423955, -0.000321537724, 7.33792245e-07, -7.32234889e-10, 2.66521446e-13,
      85443.8832, 4.53130848]
    - [2.60558298, -0.000195934335, 1.06737219e-07, -1.6423939e-11, 8.18705752e-16,
      85412.9443, 4.19238681]
- name: S
  composition: {S: 1}
  thermo:
    model: NASA7
    temperature-ranges: [200.0, 1000.0, 6000.0]
    data:
    - [2.31725616, 0.00478018342, -1.42082674e-05, 1.56569538e-08, -5.96588299e-12,
      32506.8976, 6.06242434]
    - [2.87936498, -0.000511050388, 2.53806719e-07, -4.45455458e-11, 2.66717362e-15,
      32501.3791, 3.98140647]
- name: CS
  composition: {C: 1, S: 1}
  thermo:
    model: NASA7
    temperature-ranges: [300.0, 1000.0, 5000.0]
    data:
    - [3.4039344, -0.00065773308, 6.1712157e-06, -7.3689604e-09, 2.7346738e-12,
      32689.393, 5.91106729]
    - [3.6826012, 0.00090473203, -3.6436374e-07, 6.3854294e-11, -3.6933982e-15,
      32497.49, 3.89841679]
- name: Cs
  composition: {Cs: 1}
  thermo:
    model: NASA7
    temperature-ranges: [200.0, 1000.0, 6000.0]
    data:
    - [2.50004554, -4.66833356e-07, 1.68005061e-09, -2.48218029e-12, 1.2771219e-15,
      8455.40436, 6.87573539]
    - [2.82023315, -0.000334840327, -9.82915709e-08, 1.27564369e-10, -1.46119271e-14,
      8306.39354, 5.00894042]
```
